/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AVAXGods } from "./AVAXGods";
export * as factories from "./factories";
export { AVAXGods__factory } from "./factories/AVAXGods__factory";
