// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertIcon: typeof import('./components/alert/AlertIcon.vue')['default']
    AlertInfo: typeof import('./components/alert/AlertInfo.vue')['default']
    CustomButton: typeof import('./components/CustomButton.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    OnBoard: typeof import('./components/OnBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
