// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/battle/ActionButton.vue')['default']
    AlertIcon: typeof import('./components/common/alert/AlertIcon.vue')['default']
    AlertInfo: typeof import('./components/common/alert/AlertInfo.vue')['default']
    Card: typeof import('./components/common/Card.vue')['default']
    CurrentPlayerInfo: typeof import('./components/common/CurrentPlayerInfo.vue')['default']
    CustomButton: typeof import('./components/CustomButton.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    GameInfo: typeof import('./components/battle/GameInfo.vue')['default']
    GameLoad: typeof import('./components/GameLoad.vue')['default']
    HeroCharIcon: typeof import('./components/common/HeroCharIcon.vue')['default']
    OnBoard: typeof import('./components/OnBoard.vue')['default']
    PlayerInfo: typeof import('./components/battle/PlayerInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tilt: typeof import('./components/common/Tilt.vue')['default']
  }
}
